version: "3.8"

services:
    frontend-dev:
        build:
            context: ./client
            target: builder
        ports:
            - "5173:5173"
        volumes:
            - ./client:/app
            - /app/node_modules
        working_dir: /app
        command: npm run dev
        environment:
            - VITE_API_URL=http://localhost:8080

    frontend-prod:
        build:
            context: ./client
            target: production
        ports:
            - "3000:80"
        depends_on:
            - backend-prod

    backend-dev:
        build: ./server
        ports:
            - "8080:8080"
        volumes:
            - ./server:/workspace
            - maven_cache:/root/.m2
        working_dir: /workspace
        env_file:
            - ./server/.env
        command: ./mvnw spring-boot:run
        depends_on:
            - database

    backend-prod:
        build: ./server
        ports:
            - "8080:8080"
        env_file:
            - ./server/.env
        depends_on:
            - database

    database:
        image: mysql:8.1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: debt_management
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
    maven_cache:
